"""QFPyToolbox — a Pythonic quantitative finance toolbox."""

from __future__ import annotations

__version__ = "0.1.0"

from qfpytoolbox.finance import (
    black_scholes_call,
    black_scholes_greeks,
    black_scholes_put,
    bond_convexity,
    bond_duration,
    bond_price,
    compound_interest,
    future_value,
    irr,
    npv,
    present_value,
)
from qfpytoolbox.optim import (
    efficient_frontier,
    equal_weight_portfolio,
    max_sharpe_portfolio,
    min_variance_portfolio,
    portfolio_return,
    portfolio_sharpe,
    portfolio_volatility,
    risk_parity_portfolio,
)
from qfpytoolbox.stats import (
    alpha,
    beta,
    calmar_ratio,
    conditional_var,
    correlation_matrix,
    covariance_matrix,
    excess_kurtosis,
    information_ratio,
    max_drawdown,
    mean_return,
    sharpe_ratio,
    skewness,
    sortino_ratio,
    tracking_error,
    value_at_risk,
    volatility,
)
from qfpytoolbox.timeseries import (
    annualize_returns,
    autocorrelation,
    cumulative_returns,
    drawdown_series,
    ewm_mean,
    ewm_std,
    log_returns,
    rolling_beta,
    rolling_correlation,
    rolling_max_drawdown,
    rolling_mean,
    rolling_sharpe,
    rolling_std,
    simple_returns,
)

__all__ = [
    "__version__",
    # stats
    "mean_return",
    "volatility",
    "skewness",
    "excess_kurtosis",
    "sharpe_ratio",
    "sortino_ratio",
    "max_drawdown",
    "calmar_ratio",
    "value_at_risk",
    "conditional_var",
    "information_ratio",
    "tracking_error",
    "beta",
    "alpha",
    "correlation_matrix",
    "covariance_matrix",
    # timeseries
    "rolling_mean",
    "rolling_std",
    "rolling_sharpe",
    "rolling_max_drawdown",
    "rolling_correlation",
    "rolling_beta",
    "ewm_mean",
    "ewm_std",
    "cumulative_returns",
    "log_returns",
    "simple_returns",
    "annualize_returns",
    "drawdown_series",
    "autocorrelation",
    # optim
    "min_variance_portfolio",
    "max_sharpe_portfolio",
    "efficient_frontier",
    "risk_parity_portfolio",
    "equal_weight_portfolio",
    "portfolio_return",
    "portfolio_volatility",
    "portfolio_sharpe",
    # finance
    "compound_interest",
    "present_value",
    "future_value",
    "npv",
    "irr",
    "bond_price",
    "bond_duration",
    "bond_convexity",
    "black_scholes_call",
    "black_scholes_put",
    "black_scholes_greeks",
]
